name: Jared Dillard
description: Jared Dillard is a web developer based in the Pacific North West.
meta_description: 'Jared Dillard is a web developer based in the Pacific North West.'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: 'https://jareddillard.com'
url: 'https://jareddillard.com'
author: 'Jared Dillard'
title: 'Jared Dillard'
google_analytics: 'UA-7883601-2'
repository: jdillard/personal-site

include: ["_headers"]
exclude: ["Gemfile.lock","Rakefile","Gemfile","README.md","node_modules","npm-debug.log","package.json","vendor"]

social:
  name: Jared Dillard
  links:
    - https://www.linkedin.com/in/jareddillard
    - https://github.com/jdillard
    - https://www.instagram.com/farmerofbits/

permalink: /blog/:title.html

collections:
  library:
    output: true
    permalink: /library/:title:output_ext
  crags:
    output: true
    permalink: /crags/:title:output_ext

sass:
    style: compressed
