description: Jared Dillard is a web developer based in the Pacific Time Zone.
meta_description: 'Jared Dillard is a web developer based in the Pacific Time Zone.'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: ""
domain_name: 'https://www.jareddillard.com'
url: 'https://www.jareddillard.com'
author: 'Jared Dillard'
repository: jdillard/personal-site

include: ["_headers", "_redirects", ".well-known"]
exclude: ["Gemfile.lock","Rakefile","Gemfile","README.md","node_modules","npm-debug.log","package.json","vendor"]

social:
  name: Jared Dillard
  links:
    - https://www.linkedin.com/in/jareddillard
    - https://github.com/jdillard

permalink: /blog/:title

collections:
  library:
    output: true
    permalink: /library/:title
  crags:
    output: true
    permalink: /crags/:title
  trips:
    output: true
    permalink: /trips/:title

sass:
    style: compressed
